spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://blog-test-db.cou8xa4agkom.us-east-2.rds.amazonaws.com:3306/blog
    url: jdbc:mysql://blog-db.cou8xa4agkom.us-east-2.rds.amazonaws.com:3306/blog
    username: root
    password: Aa1143101!

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

logging:
  level:
    root: warn
    edu.nyu.blog: info
  file: log/blog-pro.log

server:
  port: 8080