spring:
  thymeleaf:
    mode: HTML
    #  profiles:
    #    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1143101

    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true

logging:
  level:
    root: warn
    edu.nyu.blog: info
  file: log/blog-pro.log

server:
  port: 8081